---
# handlers file for setup-apache-role

- name: start  httpd service
  service:
     name: http --- # giving bug intensinally
     state: started
  when: ansible_os_family == "Redhat"
  Ignore_Errors: yes


- name: start apache2 service
  service:
     name: apache2
     state: started
  when: ansible_os_family == "Debian"    
